%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/kavya/Downloads/Project.xlsx
%    Worksheet: Sheet1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2018/06/21 17:43:06

%% Import the data
[~, ~, raw] = xlsread('/Users/kavya/Downloads/Project.xlsx','Sheet1');
raw = raw(2:end,:);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Create table
Project1 = table;

%% Allocate imported array to column variable names
Project1.Time_hours = data(:,1);
Project1.Time = data(:,2);
Project1.Average_SBP = data(:,3);
Project1.Average_DBP = data(:,4);
Project1.Average_PulseR = data(:,5);

%% Clear temporary variables
clearvars data raw;